name: build

on:
  pull_request:
  push:
    branches: [master]

jobs:
  tox:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    - name: install tox
      run: python -m pip install --upgrade tox virtualenv setuptools pip
    - name: run tox tests
      run: tox -e py
    - name: run tox flake8
      run: tox -e flake8
    - name: run tox pylint
      run: tox -e pylint
